blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.blog_list, name="blog_list"),
]

strava_deck/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("titles.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("blog/", include("blog.urls")),
]

titler/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("titles.urls")),
    # path("titles/", include("titles.urls")),
    path("admin/", admin.site.urls),
]

titles/urls.py
from django.urls import path

from . import views

app_name = "titles"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("delete/<int:pk>/", views.DeleteView.as_view(), name="delete"),
    path("webhook", views.strava_webhook, name="strava_webhook"),
    path("strava/callback", views.strava_callback, name="strava_callback"),
    path("strava/login", views.strava_login, name="strava_login"),
    path("strava/mobile/login", views.strava_mobile_login, name="strava_mobile_login"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("logout/", views.logged_out, name="logout"),
    path("login/", views.login_view, name="login"),
]

titles/models.py
import logging

import requests
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from strava_deck import settings


class StravaUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    athlete_id = models.IntegerField(unique=True, null=False, blank=False)


class Title(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    used_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title


class Activity(models.Model):
    title = models.ForeignKey(Title, on_delete=models.CASCADE)
    activity_id = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Token(models.Model):
    """Bearer token for API auth"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    access_token = models.CharField(max_length=255)
    refresh_token = models.CharField(max_length=255)
    expires_at = models.DateTimeField()

    def __str__(self):
        return f"{self.user} - Token"

    def is_expired(self):
        """Check if the token is expired."""
        return timezone.now() >= self.expires_at

    def refresh(self):
        """Refresh the access token using the refresh token."""
        if not self.is_expired():
            logging.info("TOKEN GOOD")
            return None

        response = requests.post(
            "https://www.strava.com/oauth/token",
            data={
                "client_id": settings.STRAVA_CLIENT_ID,
                "client_secret": settings.STRAVA_CLIENT_SECRET,
                "grant_type": "refresh_token",
                "refresh_token": self.refresh_token,
            },
        )

        if response.status_code == 200:
            token_data = response.json()
            self.access_token = token_data["access_token"]
            self.refresh_token = token_data.get("refresh_token", self.refresh_token)
            self.expires_at = timezone.now() + timezone.timedelta(
                seconds=token_data["expires_in"]
            )
            self.save()

    def save(self, *args, **kwargs):
        """Override save method to ensure that expires_at is in UTC."""
        if self.expires_at and not self.expires_at.tzinfo:
            self.expires_at = timezone.make_aware(
                self.expires_at, timezone.timezone.utc
            )
        super().save(*args, **kwargs)

titles/forms.py
from django import forms

from titles.models import Title


class TitleForm(forms.ModelForm):
    class Meta:
        model = Title
        fields = ["title"]
        widgets = {
            "title": forms.Textarea(attrs={"cols": 30, "rows": 3}),
        }

titles/views.py
import json
import logging
import time
from urllib.parse import urlencode, urlunparse

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from titles.strava import update_activity_name, create_user
from .forms import TitleForm
from .models import Title


from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


class UnsafeRedirect(HttpResponseRedirect):
    allowed_schemes = ["http", "https", "strava"]


@login_required
def index(request):
    if request.method == "POST":
        form = TitleForm(request.POST)
        if form.is_valid():
            title = form.save(commit=False)
            title.user = request.user
            title.save()
            messages.success(request, "Title saved successfully!")
            return redirect("titles:detail", pk=title.pk)
    else:
        form = TitleForm()

    title_list = Title.objects.filter(user=request.user).order_by("-created_at")
    queued_title = (
        Title.objects.filter(user=request.user)
        .filter(used_at__isnull=True)
        .order_by("-created_at")
        .last()
    )

    paginator = Paginator(title_list, 5)
    page = request.GET.get("page")

    try:
        titles = paginator.page(page)
    except PageNotAnInteger:
        titles = paginator.page(1)
    except EmptyPage:
        titles = paginator.page(paginator.num_pages)

    context = {
        "form": form,
        "titles": titles,
        "DEBUG": settings.DEBUG,
        "queued_title": queued_title,
    }
    return render(request, "titles/index.html", context)


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Title
    template_name = "titles/detail.html"


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Title
    success_url = reverse_lazy("titles:index")


@csrf_exempt
def strava_webhook(request):
    """Called upon activity updates and creates"""
    if request.method == "GET":
        return verify_webhook(request)
    elif request.method == "POST":
        return handle_event(request)
    return JsonResponse(status=405, data={"error": "Method not allowed"})


def verify_webhook(request):
    """Verifies the webhook subscription with Strava."""
    hub_mode = request.GET.get("hub.mode")
    hub_challenge = request.GET.get("hub.challenge")
    hub_verify_token = request.GET.get("hub.verify_token")

    if hub_mode == "subscribe" and hub_verify_token == settings.VERIFY_TOKEN:
        logging.info("WEBHOOK_VERIFIED")
        return JsonResponse({"hub.challenge": hub_challenge})
    else:
        return JsonResponse(status=403, data={"error": "Verification failed"})


def handle_event(request):
    """Handles the POST request for activity updates from Strava."""
    event_data = json.loads(request.body)
    event_type = event_data.get("aspect_type")
    object_type = event_data.get("object_type")
    activity_id = event_data["object_id"]
    logging.info(f"Received event: {event_type}")
    start = time.time()
    if (object_type == "activity") and (event_type == "create"):
        user = User.objects.filter(
            stravauser__athlete_id=event_data["owner_id"]
        ).first()
        update_activity_name(id=activity_id, user=user)
    logging.info(f"Event response: {event_type}, time: {time.time() - start}")
    return JsonResponse(status=200, data={"status": "Event received"})


def strava_login(request):
    """Connect with Strava button"""
    redirect_uri = request.build_absolute_uri("/strava/callback")
    params = {
        "client_id": settings.STRAVA_CLIENT_ID,
        "response_type": "code",
        "redirect_uri": redirect_uri,
        "scope": "activity:read_all,activity:write",
        "approval_prompt": "auto",
    }

    query_string = urlencode(params)
    url = urlunparse(
        ("https", "www.strava.com", "/oauth/authorize", "", query_string, "")
    )
    return redirect(url)


def strava_mobile_login(request):
    """Connect with Strava button mobile"""
    redirect_uri = request.build_absolute_uri("/strava/callback")
    params = {
        "client_id": settings.STRAVA_CLIENT_ID,
        "response_type": "code",
        "redirect_uri": redirect_uri,
        "scope": "activity:read_all,activity:write",
        "approval_prompt": "auto",
    }
    query_string = urlencode(params)

    agent = request.headers.get("User-Agent").lower()
    if "iphone" in agent or "ipad" in agent:
        return UnsafeRedirect(f"strava://oauth/mobile/authorize?{query_string}")

    android = urlunparse(
        ("https", "www.strava.com", "/oauth/mobile/authorize", "", query_string, "")
    )
    return redirect(android)


def strava_callback(request):
    """Get the authorization code from the request"""
    code = request.GET.get("code")

    response = requests.post(
        url="https://www.strava.com/oauth/token",
        data={
            "client_id": settings.STRAVA_CLIENT_ID,
            "client_secret": settings.STRAVA_CLIENT_SECRET,
            "code": code,
            "grant_type": "authorization_code",
        },
    )

    if response.status_code != 200:
        logging.info("NO success. Error in OAuth process")
        return redirect("titles:index")

    user = create_user(token_data=response.json())

    login(request, user)
    logging.info("SUCCESS!")
    return redirect("titles:index")


def about(request):
    return render(request, "titles/about.html")


def logged_out(request):
    logout(request)
    return redirect("titles:login")


def faq(request):
    return render(request, "titles/faq.html")


def login_view(request):
    if request.user.is_authenticated:
        return redirect("titles:index")

    first_five = Title.objects.filter(user__username="rhartong-redden").order_by(
        "created_at"
    )[:5]

    context = {
        "form": TitleForm(),
        "titles": reversed(first_five),
        "DEBUG": settings.DEBUG,
    }
    return render(request, "titles/login.html", context)

titles/templates/titles/about.html
{% extends 'titles/base.html' %}

{% block title %}
About Activity Title - Streamline Your Strava Activities
{% endblock %}

{% block content %}
<h1>About Activity Title</h1>

<section class="about-intro">
    <p>
        I like to add creative titles to my Strava activities but creativity comes in bursts, so I created a website to
        store activity names and update "Afternoon Run" to something else when I upload a run. This was a fun excuse
        build a Django app, use ChatGPT, and use the Strava webhook.
    </p>
    <p>
        This project was a fun excuse to build a Django app, explore the Strava API, and testdrive ChatGPT and other
        LLMs.
    </p>


</section>

<section class="about-details">
    <h2>How It Works</h2>
    <p>
        Create an account or log back in by clicking the "Connect with Strava" button.
        Create your activity titles on this site. Then, when you upload a new activity to Strava, Activity Title
        automatically updates it with your chosen title. Deleting a title here doesn't affect your Strava. And, of
        course, all your data stays on Strava.
    </p>

    <h2>Current Features</h2>
    <ul>
        <li>Create an account using Strava Connect on desktop and mobile</li>
        <li>Create and delete titles</li>
        <li>Syncing title to Strava</li>
        <li>See what's queued up</li>
    </ul>

    <h2>Future Plans</h2>
    <p>
        This is basically feature-complete. However, here are some features I'm considering:
    </p>

    <ul>
        <li>Handling expired tokens and creating a logoff/login button</li>
        <li>Reordering your title list</li>
        <li>Integrate with Garmin to sync that rare "Productive" training status</li>
    </ul>
</section>

<section class="about-contact">
    <h2>Get in Touch</h2>
    <p>
        Have questions, a bug report, or feature requests? Send me an email!
    </p>
    <p>Email: <a href="mailto:roryhr@gmail.com">roryhr@gmail.com</a></p>
    <p>I almost forgot, check me out on <a href="https://www.strava.com/athletes/23193264">Strava</a> too. Cheers!</p>
    <p>You can support me at <a
            href="https://paypal.me/roryhr" target="_blank">paypal.me/roryhr</a></p>
</section>
{% endblock %}

titles/templates/titles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Activity Title{% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    {% if not DEBUG %}
    <script defer src="https://cloud.umami.is/script.js"
            data-website-id="a3c6a698-e1ff-4445-ba28-983c0a18f44d"></script>
    {% endif %}
</head>
<body>
<header>
    <h1>Activity Title</h1>
    <nav>
        <a href="{% url 'titles:index' %}">Home</a>
        <a href="{% url 'titles:about' %}">About</a>
        <a href="{% url 'titles:faq' %}">FAQ</a>
        <a href="{% url 'blog:blog_list' %}">Blog</a>
    </nav>
</header>

<main>
    {% block content %}
    Default content if no block is overridden
    {% endblock %}

    <section class="disclaimer">
        <img src="{% static 'img/api_logo_cptblWith_strava_horiz_gray.png' %}" alt="Login with Strava">
        <p class="affiliation-note">Activity Title is not affiliated with Strava. We use the Strava API to provide
            these features, but we are an independent application.</p>
    </section>
</main>

<footer>
    <p>&copy; 2026 Rory Hartong-Redden</p>
</footer>
</body>
</html>

titles/templates/titles/detail.html
{% extends 'titles/base.html' %}

{% block title %}
Activity Title - Detail
{% endblock %}

{% block content %}
{% load static %}
<h1>{{ title.title|linebreaksbr }}</h1>
<p class="created-at">Created at {{ title.created_at }}</p>

{% if title.used_at %}
<p class="created-at">Linked to Strava on {{ title.used_at }}</p>
{% endif %}

<h2>Linked Activity:</h2>
<ul class="titles">
    {% for activity in title.activity_set.all %}
    <li>
        {% if activity.activity_id %}
        <a href="https://www.strava.com/activities/{{ activity.activity_id }}" target="_blank">
            Strava Activity #{{ activity.activity_id }}
        </a>
        {% endif %}
    </li>
    {% empty %}
    <p>Once this title is synced to Strava you'll see a link to the activity.</p>
    {% endfor %}
</ul>

<div class="button-container">
    <a href="{% url 'titles:index' %}" class="btn-back">← Back to Index</a>

    <form method="post" action="{% url 'titles:delete' title.id %}" onsubmit="return confirmDelete()">
        {% csrf_token %}
        <button type="submit" class="btn-delete">Delete</button>
    </form>
</div>

<script>
    function confirmDelete() {
        return confirm("Are you sure you want to delete this title?");
    }
</script>
{% endblock %}

titles/templates/titles/faq.html
{% extends 'titles/base.html' %}

{% block title %}Frequently Asked Questions - Activity Title{% endblock %}

{% block content %}
<h1>Frequently Asked Questions</h1>

<section class="faq">
    <h2>General</h2>
    <details>
        <summary>What is Activity Title?</summary>
        <p>I like to add creative titles to my Strava activities but creativity comes in bursts, so I created this
            website to store activity names and update "Afternoon Run" to something else when I upload a run.
            This was a fun excuse build a Django app, experiment with ChatGPT for some coding help, and use the Strava
            API.
        </p>
    </details>
    <details>
        <summary>Where's the AI?</summary>
        <p>There's no AI here. You need to come up with your own names. All we do is store and sync them.</p>
    </details>
    <details>
        <summary>How does it work?</summary>
        <p>You create and save activity titles in advance. When you upload a new activity to Strava, Activity Title
            automatically updates it with the next one in the queue using Strava's webhook API.</p>
    </details>
    <details>
        <summary>Is Activity Title free?</summary>
        <p>Yes! This website is a one-trick pony that doesn't cost much to run. You can support me at <a
                href="https://paypal.me/roryhr" target="_blank">paypal.me/roryhr</a></p>
    </details>
    <details>
        <summary>Have you heard of the other Strava Apps?</summary>
        <p>Yeah, there are lots of awesome apps to help manage your Strava. Here are some of the popular ones:</p>
        <ul>
            <li><a href="https://activityfix.com">ActivityFix</a></li>
            <li><a href="https://www.bandok.com">Bandok</a></li>
            <li><a href="https://onlypuns.xyz">Only Puns</a></li>
            <li><a href="https://klimat.app">Klimat</a></li>
        </ul>
    </details>

    <h2>Strava Integration</h2>
    <details>
        <summary>What Strava permissions does Activity Title require?</summary>
        <p>Activity Title requires permission to read and write activity data. This is necessary to update your activity
            titles.</p>
    </details>
    <details>
        <summary>What happens to my Strava data?</summary>
        <p>Activity Title only stores your activity titles and the associated Strava activity ID.
            Basically, your Strava data stays on Strava. We don't change your privacy settings.
        </p>
    </details>
    <details>
        <summary>What happens if I don't authorize Activity Title to view my private activities?</summary>
        <p>Unfortunately, the app won't work. But you still log in.</p>
    </details>
    <h2>Account and Access</h2>
    <details>
        <summary>How can I get an account?</summary>
        <p>Click the "Connect with Strava" button.</p>
    </details>

    <h2>Other</h2>
    <details>
        <summary>Who created Activity Title?</summary>
        <p>Activity Title was created by Rory Hartong-Redden.</p>
    </details>
</section>
{% endblock %}

titles/templates/titles/index.html
{% extends 'titles/base.html' %}

{% block title %}
Activity Title - Home
{% endblock %}

{% block content %}
{% load static %}
{% block messages %}
<ul id="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endblock %}

<section class="titles">
    {% if user.is_authenticated %}
    <p>Welcome back, {{ user.first_name }}!</p>
    {% else %}
    <p>Welcome to the Activity Title App!</p>
    {% endif %}
</section>

<section class="titles">
    <h1>Create New Title</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    <h2>List of Titles</h2>
    <ul>
        {% for title in titles %}
        <li>
            <a href="{% url 'titles:detail' title.id %}" class="title-link">{{ title.title|linebreaksbr }}</a>
            <p class="created-at">Created at: {{ title.created_at }}</p>
            {% if title.used_at %}
            <p class="created-at">Used at: {{ title.used_at }}</p>
            {% endif %}

            {% if title == queued_title %}
            <span style="color: gold;">★</span>
            <small>Queued to sync <br></small>
            {% endif %}
        </li>
        {% empty %}
        <li>No titles are available.</li>
        {% endfor %}
    </ul>

    <div class="pagination">
        {% if titles.has_previous %}
        <a href="?page=1" class="pagination-link">&laquo; first</a>
        <a href="?page={{ titles.previous_page_number }}" class="pagination-link">previous</a>
        {% endif %}

        <span class="page-info">Page {{ titles.number }} of {{ titles.paginator.num_pages }}</span>

        {% if titles.has_next %}
        <a href="?page={{ titles.next_page_number }}" class="pagination-link">next</a>
        <a href="?page={{ titles.paginator.num_pages }}" class="pagination-link">last &raquo;</a>
        {% endif %}
    </div>
</section>

<section class="strava-login">
    <p>Connect with Strava to login</p>
    <a href="{% url 'titles:strava_login' %}" class="strava-button">
        <img src="{% static 'img/btn_strava_connectwith_orange.png' %}" alt="Login with Strava">
    </a>
    <p class="affiliation-note">We are not affiliated with Strava.</p>
</section>
{% endblock %}

titles/templates/titles/login.html
{% extends 'titles/base.html' %}
{% load static %}

{% block title %}Activity Title - Login{% endblock %}

{% block content %}
<section class="titles">
    <h1>Create New Title</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
    <h2>List of Titles</h2>
    <p>This is demo data. Create an account make your own list.</p>
    <ul>
        {% for title in titles %}
        <li>
            <a href="{% url 'titles:detail' title.id %}" class="title-link">{{ title.title|linebreaksbr }}</a>
            <p class="created-at">Created at: {{ title.created_at }}</p>
            <p class="created-at">Used at: {{ title.used_at }}</p>
        </li>
        {% empty %}
        <li>No titles are available.</li>
        {% endfor %}
    </ul>
</section>

<div class="strava-buttons-container">
    <section class="strava-login">
        <p>Web login. Click here if you use the Strava website.</p>
        <a href="{% url 'titles:strava_login' %}" class="strava-button">
            <img src="{% static 'img/btn_strava_connectwith_orange.png' %}" alt="Login with Strava">
        </a>
    </section>

    <section class="strava-login">
        <p>Mobile login. Click here if you use the Strava mobile app.</p>
        <a href="{% url 'titles:strava_mobile_login' %}" class="strava-button">
            <img src="{% static 'img/btn_strava_connectwith_orange.png' %}" alt="Login with Strava (Mobile)">
        </a>
    </section>
</div>
{% endblock %}